### ISSUE TITLE
Re:Apps that are not working/ deprecated/ no longer maintained/ harmful 

### ISSUE THREAD

**Issue by luong-komorebi** [luong-komorebi/Awesome-Linux-Software#195]
Hi all visitors, if you are using an app that is not working anymore or it has been deprecated/ no longer maintained -> **PLEASE NOTIFY ME BY OPENING AN ISSUE.** Be aware that not all deprecated/ no longer maintained app is bad. I will consider whether it is still worthy to be on the list and if there is any fork/ replacement that gets the job done better.  
******
In the case of harmful apps, it would be nice if you specify in what condition you did find or suspect that the app is doing something pernicious/ where you downloaded it (official PPA/ official page/ third party page)/ how it did affect you and your computer..... + any information that you think may help me reproduce the issue you encountered.
******
Have a nice day :smile_cat:

**Comment by LeaVRun45** [comment]
> Hi all visitors, if you are using an app that is not working anymore or it has been deprecated/ no longer maintained -> **PLEASE NOTIFY ME BY OPENING AN ISSUE.** Be aware that not all deprecated/ no longer maintained app is bad. I will consider whether it is still worthy to be on the list and if there is any fork/ replacement that gets the job done better.
> 
> In the case of harmful apps, it would be nice if you specify in what condition you did find or suspect that the app is doing something pernicious/ where you downloaded it (official PPA/ official page/ third party page)/ how it did affect you and your computer..... + any information that you think may help me reproduce the issue you encountered.
> 
> Have a nice day

Yeh bad app, I need help!

**Comment by LeaVRun45** [comment]
@LeaVRun45 
I like jorney mess a lot of have fun
Like children fall off and get up!
