### ISSUE TITLE
some softwares

### ISSUE THREAD

**Issue by levinit** [luong-komorebi/Awesome-Linux-Software#242]
- [ocssotre](https://www.linux-apps.com/p/1175480/)   (github https://github.com/opendesktop/ocsstore)
linuxapp.com app, download many linux sources,eg. softwares,DE themes,icon themes,cursor themes,wallpaper……

- [gisto](http://www.gistoapp.com/)
a GUI github gist manager

- [github-desktop](https://github.com/gengjiawen/desktop/releases)
github-desktop  linux version

- [Stunt Rally](http://stuntrally.tuxfamily.org/)
3D racing game

-  [Cataclysm: Dark Days Ahead](http://www.cataclysmdda.com/) (github: https://github.com/CleverRaven/Cataclysm-DDA)
 an actively maintained roguelike set in a post-apocalyptic world, forked from the original

**Comment by LewisVo** [comment]
Thank you @levinit , it's nice to see you again. Please leave me some time to try these apps out. Until then I am gonna leave this open

**Comment by LewisVo** [comment]
I would like to confirm something : 
- Github desktop is in beta. Not added. Even their website doesn't mention anything about Linux. (Electron seems selective towards OS now lolz) 
![](http://imgur.com/2BbXyjxl.png) 
- Stunt rally : Too laggy on my computer. Very sorry. Wait until I can borrow a newer one. 
- Cataclysm: Dark Days Ahead:  ... OMFG .... I don't know which kind of subcategory this game should fall into, pls recommend. 

Others: 59e9a20117e57d05d50ab1015bec07e6576e0329

**Comment by levinit** [comment]
[grsync](http://www.opbyte.it/grsync/)   a sync gui app

**Comment by levinit** [comment]
Recently I found a awesome app ,[zazu](https://github.com/tinytacoteam/zazu) (linux/mac/win)  it's cool.
> A fully extensible and open source launcher for hackers, creators and dabblers. 
---
[veracrypt](http://veracrypt.codeplex.com/)-- an open-source utility used for on-the-fly encryption (OTFE),see [wikipeida-veracrypt](https://en.wikipedia.org/wiki/VeraCrypt).
 Maybe some people need a encryption tool like this,  😄 It is said that  FBI spent a year‘s time can not crack the file crypt by veracrypt.
---
cataclysm is a end of the survial game , but there is not a suitable subctegory for it in this project，how about Miscellaneous …😂………

**Comment by LewisVo** [comment]
@levinit I will check them out soon. Sorry for the delay, I got busy recently.

**Comment by luzpaz** [comment]
[FreeCAD](https://freecadweb.org)

**Comment by levinit** [comment]
[multibootusb](http://multibootusb.org/)    Boot multiple live Linux distros from a usb flash drive.
> MultiBootUSB is a cross platform software written in python which allows you to install multiple live linux on a USB disk non destructively and option to uninstall distros. Try out the world's first true cross platform multi boot live usb creator for free.

**Comment by levinit** [comment]
RTS game: [megalest](https://megaglest.org)      Fork of Glest, a 3D real-time strategy game in a fantastic world

**Comment by SaintFenix** [comment]
@levinit I've used Multibootusb great tool.

**Comment by onlurking** [comment]
Cataclysm: DDA is a `roguelike` game.

**Comment by levinit** [comment]
I am coming!
[wunderlistux](https://github.com/edipox/wunderlistux)   
> An electron wrapper for wunderlist made with ❤️ for Linux (specially for elementary OS) 
it has a lower memeory footprint than  chromium-wunderlist(https://chrome.google.com/webstore/detail/wunderlist-for-chrome/ojcflmmmcfpacggndoaaflkmcoblhnbh?utm_source=chrome-ntp-icon)

**Comment by SaintFenix** [comment]
I personally use Grsync, veracrypt and multibootusb, and can vouch for their quality, the others I don't have any experience with.

If you find that enough though @LewisVo I'll put together a pull request for at least those three. I can also lend a hand testing the others if you like.

**Comment by levinit** [comment]
[anki](https://apps.ankiweb.net/)     a cross-platform 
> Friendly, intelligent flash cards.Remembering things just became much easier.
also see https://pkgs.org/download/anki

**Comment by LewisVo** [comment]
Anlki added. Thank you @levinit

**Comment by yernhi** [comment]
Image Management
- [XnView MP](https://www.xnview.com/en/xnviewmp/) - A cross-platform media browser, viewer and converter, free for private or educational use.

**Comment by yernhi** [comment]
Deepin Store provides some original software (though they are designed for Deepin OS): https://www.deepin.org/en/original/

**Comment by levinit** [comment]
pretending to be a hacker in Hollywood films 😂  [hollywood](https://github.com/dustinkirkland/hollywood)

**Comment by SaintFenix** [comment]
That was actually the first command line program I ever used that produced sound. It scared the living daylights out of me. I do love it however, it's a classic like: Cmatrix, and cowsay.

**Comment by levinit** [comment]
[etckeeper](https://etckeeper.branchable.com/)   [archwiki-etckeeper](https://wiki.archlinux.org/index.php/etckeeper)
backup /etc easier
> etckeeper is a collection of tools to let /etc be stored in a git, mercurial, bazaar or darcs repository. This lets you use git to review or revert changes that were made to /etc. Or even push the repository elsewhere for backups or cherry-picking configuration changes.

**Comment by lausek** [comment]
[scrot](https://github.com/dreamer/scrot) - minimalistic command line screenshot capturing tool

**Comment by mangalbhaskar** [comment]
@luong-komorebi 
Very interesting and useful repo!

In the same lines, I have many tool chains and scripts for setting up these tools  and also more listing of software specifically from [Computer Vision, Image Processing, Graphics, CAD, 3D, VFX, Deep Learning, GIS](https://github.com/mangalbhaskar/technotes/blob/master/README.md#getting-started-for-image-processing-computer-vision-machine-learning-and-deep-learning-for-gis) domain.

I would suggest an initiative to provide standard shell scripts for installation of many of such tools, that help people to quickly adopt and save time for many.

I would love to contribute/collaborate with you to consolidate and provide installation scripts.

* [List of Tools & their Installation scripts for Ubuntu 16.04 LTS, 18.04 LTS](https://github.com/mangalbhaskar/linuxscripts/blob/master/README.md)
* [List of some more tools](https://github.com/mangalbhaskar/technotes/blob/master/tools.md)
* [CAD tools](https://github.com/mangalbhaskar/technotes/blob/master/cad-tools.md)

**Comment by chrunchyjesus** [comment]
@mangalbhaskar There are some very interesting software you have listed.

That aside I am not really sure whether providing installation scripts makes sense, since there are all those package managers and different package names under different distros in the way.

**Comment by levinit** [comment]
> @mangalbhaskar There are some very interesting software you have listed.
> 
> That aside I am not really sure whether providing installation scripts makes sense, since there are all those package managers and different package names under different distros in the way.

**Comment by jodumont** [comment]
FWI @levinit 

#### etckeeper could auto push and store all change on a remote git such as github/gitlab
https://coderwall.com/p/v1agsg/installing-etckeeper-to-store-config-with-autopush-to-git-in-ubuntu-14-04-lts

> category:Data Backup and Recovery
> application: [etckeeper](https://etckeeper.branchable.com/) [archwiki-etckeeper](https://wiki.archlinux.org/index.php/etckeeper)
> use git backup `/etc`
> 
> > etckeeper is a collection of tools to let /etc be stored in a git, mercurial, bazaar or darcs repository. This lets you use git to review or revert changes that were made to /etc. Or even push the repository elsewhere for backups or cherry-picking configuration changes.
