### ISSUE TITLE
The empty #Other distros# section future

### ISSUE THREAD

**Issue by JuPlutonic** [luong-komorebi/Awesome-Linux-Software#433]
If it happened, what you guy start to fill the "Other distros" section in this list, will awesome list be overweighted with disrtos related information?
IMHO better to put again https://distrowatch.com/ link, link to https://www.reddit.com/r/FindMeADistro/ and give links to wikipedia linux disrto table: https://en.wikipedia.org/wiki/List_of_Linux_distributions and to  https://en.wikipedia.org/wiki/Category:Linux_distributions)

**Comment by luong-komorebi** [comment]
Your concerns really match mine. I plan to remove that section in recent future. Thank you for raising your voice ❤️

**Comment by luong-komorebi** [comment]
@JuPlutonic Just keep it open. I will close it when the commit is on master ;)

**Comment by luong-komorebi** [comment]
I believe this is solved in dc11ef7546316938558714c203e9811c14c43cab , where I decided that all set up and other parts that falls out of this list's main interest should be deprecated.
