### ISSUE TITLE
signal-desktop

### ISSUE THREAD

**Issue by aureooms** [luong-komorebi/Awesome-Linux-Software#473]
See https://signal.org/download.

**Comment by luong-komorebi** [comment]
Hi. Sorry but this and all your issues in #474 #475 are not helpful to me.
For the purpose of an issue, please read https://help.github.com/en/github/managing-your-work-on-github/about-issues.
If you want to suggest an app, please view https://github.com/luong-komorebi/Awesome-Linux-Software/blob/master/CONTRIBUTING.md
