### ISSUE TITLE
Replace Franz with Ferdi

### ISSUE THREAD

**Issue by L4yer** [luong-komorebi/Awesome-Linux-Software#507]
Hello could I suggest that franz be replaced with Ferdi.

https://getferdi.com/

Thank you

**Comment by luong-komorebi** [comment]
it s a fork. I would like to keep them both. Can you open a PR to help me add Ferdi?

**Comment by DimitrisPa** [comment]
Thank you for your contribution. Add Ferdium (Fork of Ferdi) #577.
