### ISSUE TITLE
Daily-Reddit-Wallpaper is no longer maintained

### ISSUE THREAD

**Issue by federicotorrielli** [luong-komorebi/Awesome-Linux-Software#522]
In the CLI utils, I suggest to replace it with my personal fork: https://github.com/federicotorrielli/Daily-Reddit-Wallpaper that I'm currently going to maintain it for a year or so.

**Comment by luong-komorebi** [comment]
Of course. You are welcome to open a PR replacing the original with your  fork. I saw your issue on the original repo https://github.com/ssimunic/Daily-Reddit-Wallpaper/issues/48 and seems like the silence of the authors is enough for us to do this

**Comment by federicotorrielli** [comment]
> Of course. You are welcome to open a PR replacing the original with your  fork. I saw your issue on the original repo https://github.com/ssimunic/Daily-Reddit-Wallpaper/issues/48 and seems like the silence of the authors is enough for us to do this 

Thanks, I will do a PR tomorrow.
