### ISSUE TITLE
Add Official Chat Clients

### ISSUE THREAD

**Issue by itsnotsaved** [luong-komorebi/Awesome-Linux-Software#566]
**Official Chat Clients**
- Revolt Chat - Communication is critical, Privacy is essential. (1:1 opensource alternative to discord)
https://revolt.chat/ https://github.com/revoltchat#download-links
https://flathub.org/apps/details/chat.revolt.RevoltDesktop

- Zulip - Chat for distributed teams
https://zulip.com/apps/ https://flathub.org/apps/details/org.zulip.Zulip

- Twake - https://twake.app/
https://github.com/linagora/Twake-Desktop

- RocketChat - https://rocket.chat/
https://snapcraft.io/rocketchat-desktop

- Mattermost - https://mattermost.com/
https://flathub.org/apps/details/com.mattermost.Desktop

- Zoho Cliq - Streamline your team communication
https://www.zoho.eu/cliq/
https://www.zoho.com/cliq/desktop/linux.html

- QQ - Get on QQ. Get on the world
https://im.qq.com/index https://im.qq.com/linuxqq/index.html
https://im.qq.com/linuxqq/download.html

**3rd party Clients**
- Electronic WeChat - Desktop chat client for WeChat
https://www.wechat.com/ https://snapcraft.io/electronic-wechat

**Comment by DimitrisPa** [comment]
Thank you for your contribution, most of them added to the list.
