### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by zu1fIq4r** [luong-komorebi/Awesome-Linux-Software#742]
I was installing zenmap but it won't start so then i watched some yt videos and found a solution. 
When I tried to installing those deb packages then this happened. 
Plz help 

└─$ sudo dpkg -i python-gobject-2_2.28.6-14ubuntu1_amd64.deb
(Reading database ... 412258 files and directories currently installed.)
Preparing to unpack python-gobject-2_2.28.6-14ubuntu1_amd64.deb ...
Unpacking python-gobject-2 (2.28.6-14ubuntu1) over (2.28.6-14ubuntu1) ...
dpkg: dependency problems prevent configuration of python-gobject-2:
 python-gobject-2 depends on libffi7 (>= 3.3~20180313); however:
  Package libffi7 is not installed.

dpkg: error processing package python-gobject-2 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.37-5) ...
Errors were encountered while processing:
 python-gobject-2

**Comment by FabioLolix** [comment]
Please ask in your distribution forum
