### ISSUE TITLE
Music Player with PITCH

### ISSUE THREAD

**Issue by TommyLuna** [luong-komorebi/Awesome-Linux-Software#750]
Hi people.
I would like to create a music player but with a pitch. 
This is easy o it is impossible? 
many colleagues tell me that it cannot be done....

**Comment by sonic2kk** [comment]
This repository is for tracking/documenting useful software available for Linux distributions, it doesn't actually host any software. It's not really a forum for discussing software development, you may have more success asking around on forums related to whatever technology you're planning to work with :-)
